kind: Schedule
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: {namespace}
  name: {name}
spec:
  schedule: {schedule}
  startingDeadlineSeconds: null
  concurrencyPolicy: Forbid
  historyLimit: {historyLimit}
  type: NetworkChaos
  networkChaos:
    selector:
      namespaces:
        - {namespace}
      labelSelectors:
        app: {app}
      pods:
        default:
          {pods}
    mode: all
    action: delay
    duration: {duration}
    delay:
      latency: {latency}
      correlation: '{correlation}'
      jitter: {jitter}
    direction: to
    target:
      selector:
        namespaces:
          - {namespace}
        labelSelectors:
          app: {targetapp}
        pods:
          default:
            {targetpods}
      mode: all