kind: Schedule
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: {namespace}
  name: {name}
spec:
  schedule: {schedule}
  startingDeadlineSeconds: null
  concurrencyPolicy: Forbid
  historyLimit: {historyLimit}
  type: PodChaos
  podChaos:
    selector:
      namespaces:
        - {namespace}
      labelSelectors:
        app: {app}
      pods:
        default:
          {pods}
    mode: all
    action: pod-failure
    duration: {duration}